### PR TITLE
Add filter for custom route namespace.

### PR DESCRIPTION
**Pull request by wpamitkumar**
Addresses [#4 ](https://github.com/dominic-ks/bdvs-password-reset/issues/4)

- Added Custom Namespace for the REST route.

**Usage**

add_filter( 'bdpwr_route_namespace' , function( $route_namespace ) {
	return 'xyz/v1';
}, 10 , 1 );

### CODE REVIEW

**Comment by wpamitkumar** [comment]
Hi @dominic-ks, Please review the PR. [#6  ]

**Comment by dominic-ks** [comment]
@wpamitkumar Hello, thanks for the PR. This needs to be added to two other files as well though:

- /inc/api/api.route.set-password.php
- /inc/api/api.route.validate-code.php

And also to both readme files. You happy to do those?

**Comment by wpamitkumar** [comment]
@dominic-ks I fixed on both files and README files also. :)

**Comment by dominic-ks** [comment]
@wpamitkumar Awesome thanks for contributing! I've merged this into the master branch, got a few things I'm working on that I need to finish before I push the nest version to wp.org FYI.

**Pull request merged**
